### ISSUE TITLE
Misleading error message when pattern matching against incorrect Json AST

### ISSUE THREAD

**Issue by jedesah** [propensive/rapture#148]
I am running into this compile error:

```
abstract type pattern D is unchecked since it is eliminated by erasure
  response = json => json must beLike { case json""" { "out": $outValue, "phases": $outPhases }""" =>
                                             ^
```

**Comment by jedesah** [comment]
Could it be because the `json` value in the above expression is of type `argonaut.Json` instead of `rapture.json.Json`? I read something in the docs about the conversion happening automatically, but I am still a little sceptical of that. Maybe it's an entirely different issue though, just brainstorming here.

**Comment by jedesah** [comment]
I can confirm that the above hypothesis was the issue. Perhaps a better error message would be in order, but maybe that is not easily fixed. I would not be offended if someone were to close this issue for lack of severity.

**Comment by propensive** [comment]
Hi @jedesah,
Yes, this looks like it's because you're trying to match against a non-Rapture `Json` type. I think you could wrap the original `json` value as `Json(json)`, and it should work.

I'll close the issue, though. In this case, there's not a lot we can do about the error message... :(

(Feel free to carry on the discussion, here, though!)
