### ISSUE TITLE
Some(null) returned for Option(json"""{"field":null}""".field)

### ISSUE THREAD

**Issue by sscarduzio** [propensive/rapture#183]
When a JSON object has a null field, pattern matching fails. Trying to see why, I get this surreal result:

``` scala
scala> Option(json"""{"a":null}""".a)
res1: Option[rapture.json.Json] = Some(null)
```

The expected result would be of course None. From my experience, things like Some(null) are avoided never directly instantiating any `Some` and preferring `Option`. I.e.:

```
val x = ...
Some(x) // NO
Option(x) // YES
```

I'm curious to know if this bug can be brought back to this programming principle (but knowing @propensive, probably will be some macro sci-fi as usual 😂 )

**Comment by propensive** [comment]
I think the surreal result is actually just misleading! The `null` you can see is a JSON null, not a JVM null, so it's a perfectly valid `Json` value, and the `toString` just happens to be `"null"`. Try dereferencing it and see what happens... ;)

**Comment by sscarduzio** [comment]
Wow. Ok this was indeed quite misleading, I wonder if the Json null should be named something like JsonNull or JNull or Null, rather than "null".

**Comment by propensive** [comment]
It can't really... because `null` is how null is represented in JSON, i.e. you can always call `toString` on a `Json` value, and you'll get valid JSON.

I've wondered before whether I should make the `toString` method wrap the output in `json""`, so that it's actually valid copy/pastable Scala code. This could break existing code, though it would encourage people to use `Json.format` instead of `toString` for outputting JSON.

**Comment by propensive** [comment]
So, under this scheme, your example would look like:

``` scala
scala> Option(json"""{"a":null}""".a)
res1: Option[rapture.json.Json] = Some(json"null")
```

**Comment by sscarduzio** [comment]
Makes sense, this modified toString will avoid confusion and still be useful as code. Thanks!

**Comment by propensive** [comment]
Ok, I'll make the change now! ;)
