### ISSUE TITLE
Json.format writes 'undefined' for empty options (play-backend)

### ISSUE THREAD

**Issue by johannegger** [propensive/rapture#206]
this code shows the problem: 

```
import rapture.json._
import formatters.compact._
import jsonBackends.play._

case class Foo(param1:Option[String]=None,param2:Option[Int]=None)

Json.format(Json(Foo()))
```

the resulting String is `{"param1":undefined,"param2":undefined}` which doesn't look like a valid json and other backend fail to parse it.

**Comment by mielientiev** [comment]
Hi @johannegger 
Thanks for reporting a bug. I've checked that at the current dev (M7) version and it was fixed. The root cause was an incorrect implementation of `isNull` method for `PlayAst`.

Also, I found that `isNull` method for `JacksonAst` also has a bug. I will provide a fix for Jackson + add tests today
Now expected behaviour is:

```
case class Foo(param1:Option[String]=None,param2:Option[Int]=None)

Json.format(Json(Foo()))  // result: "{}"

Json.format(Json(Foo(param2 = Some(20))))  // result: "{"param2": 20}"
```
